### ISSUE TITLE
Blank css file?

### ISSUE THREAD

**Issue by hluposti** [statamicthemes/statarkers-theme#12]
Hi, is this supposed to be blank?

https://github.com/statamicthemes/statarkers-theme/blob/original/_themes/statarkers/css/statarkers.css

**Comment by garethredfern** [comment]
Hi Yes, the "original" branch is the non-styled version. If you want some basic styles and my Sass framework you will need the master branch.

**Comment by hluposti** [comment]
I thought so, thanks for clarifying!
